annotations:
  max_scale_version: 25.04.1
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 240420.0.0
dependencies:
  - name: common
    version: 23.0.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: PhotoPrism® is a server-based application for browsing, organizing and sharing your personal photo collection
home: https://truecharts.org/charts/stable/photoprism
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoprism.webp
keywords:
  - photos
  - photoprism
  - pictures
  - sharing
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: john@jrobe.me
    url: https://jrobe.me
name: photoprism
sources:
  - https://github.com/photoprism/photoprism
  - https://github.com/jrobe/charts/tree/master/charts/development/photoprism
  - https://hub.docker.com/r/photoprism/photoprism
type: application
version: 23.0.0
