image:
  repository: bitnami/mariadb
  pullPolicy: IfNotPresent
  tag: 11.3.2@sha256:a4fcb09e1c7520845b20b2dee82164d66cbbb64ef74df7c0727f432149b4f446

includeCommon: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MARIADB_PASSWORD: "{{ .Values.password }}"
            MARIADB_ROOT_PASSWORD: "{{ .Values.rootPassword }}"
            MARIADB_USER: "{{ .Values.mariadbUsername }}"
            MARIADB_DATABASE: "{{ .Values.mariadbDatabase }}"
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"
            readiness:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"
            startup:
              enabled: true
              type: exec
              command:
                - /bin/bash
                - -ec
                - "until /opt/bitnami/scripts/mariadb/healthcheck.sh; do sleep 2; done"
service:
  main:
    ports:
      main:
        port: 3306
        targetPort: 3306
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
persistence:
  data:
    enabled: true
    mountPath: "/bitnami/mariadb"
mariadbUsername: "test"
mariadbDatabase: "test"
## DEVNOTE: These password defaults always need to match common
rootPassword: "PLACEHOLDERROOTPASSWORD"
password: "PLACEHOLDERPASSWORD"
portal:
  open:
    enabled: false
