remote: origin
target-branch: main
helm-extra-args: --timeout 600s --debug
chart-yaml-schema: .github/ct-install-config/chart_schema.yaml
chart-dirs:
  - charts/stable
  - charts/incubator
  - charts/premium
  - charts/system
excluded-charts: []
kubectl-timeout: 120s
